import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import React from 'react'

import { cn } from '@/lib/utils'
import { fontJakarta } from '@/styles/font'

export const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    'bg-background min-h-screen font-sans antialiased',
                    fontSans.variable,
                    fontJakarta.variable
                )}
            >
                {children}
            </body>
        </html>
    )
}
